package com.sample.domain;

// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbFaq generated by hbm2java
 */
@Entity
@Table(name = "TB_FAQ", schema = "dbo", catalog = "STAB_DEV")
public class TbFaq implements java.io.Serializable {

	private long faqQuestionId;
	private TbProgram tbProgram;
	private String faqStrQuestion;
	private String faqStrAnswer;

	public TbFaq() {
	}

	public TbFaq(long faqQuestionId) {
		this.faqQuestionId = faqQuestionId;
	}

	public TbFaq(long faqQuestionId, TbProgram tbProgram,
			String faqStrQuestion, String faqStrAnswer) {
		this.faqQuestionId = faqQuestionId;
		this.tbProgram = tbProgram;
		this.faqStrQuestion = faqStrQuestion;
		this.faqStrAnswer = faqStrAnswer;
	}

	@Id
	@Column(name = "FAQ_QUESTION_ID", unique = true, nullable = false)
	public long getFaqQuestionId() {
		return this.faqQuestionId;
	}

	public void setFaqQuestionId(long faqQuestionId) {
		this.faqQuestionId = faqQuestionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FAQ_PGM_ID_FK")
	public TbProgram getTbProgram() {
		return this.tbProgram;
	}

	public void setTbProgram(TbProgram tbProgram) {
		this.tbProgram = tbProgram;
	}

	@Column(name = "FAQ_STR_QUESTION", length = 500)
	public String getFaqStrQuestion() {
		return this.faqStrQuestion;
	}

	public void setFaqStrQuestion(String faqStrQuestion) {
		this.faqStrQuestion = faqStrQuestion;
	}

	@Column(name = "FAQ_STR_ANSWER", length = 1000)
	public String getFaqStrAnswer() {
		return this.faqStrAnswer;
	}

	public void setFaqStrAnswer(String faqStrAnswer) {
		this.faqStrAnswer = faqStrAnswer;
	}

}
