package com.sample.domain;

// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbLocationImages generated by hbm2java
 */
@Entity
@Table(name = "TB_LOCATION_IMAGES", schema = "dbo", catalog = "STAB_DEV")
public class TbLocationImages implements java.io.Serializable {

	private long imgLocIdPk;
	private TbProgram tbProgram;
	private byte[] imgLocImage;

	public TbLocationImages() {
	}

	public TbLocationImages(long imgLocIdPk) {
		this.imgLocIdPk = imgLocIdPk;
	}

	public TbLocationImages(long imgLocIdPk, TbProgram tbProgram,
			byte[] imgLocImage) {
		this.imgLocIdPk = imgLocIdPk;
		this.tbProgram = tbProgram;
		this.imgLocImage = imgLocImage;
	}

	@Id
	@Column(name = "IMG_LOC_ID_PK", unique = true, nullable = false)
	public long getImgLocIdPk() {
		return this.imgLocIdPk;
	}

	public void setImgLocIdPk(long imgLocIdPk) {
		this.imgLocIdPk = imgLocIdPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IMG_PGM_ID_FK")
	public TbProgram getTbProgram() {
		return this.tbProgram;
	}

	public void setTbProgram(TbProgram tbProgram) {
		this.tbProgram = tbProgram;
	}

	@Column(name = "IMG_LOC_IMAGE")
	public byte[] getImgLocImage() {
		return this.imgLocImage;
	}

	public void setImgLocImage(byte[] imgLocImage) {
		this.imgLocImage = imgLocImage;
	}

}
