package com.sample.domain;

// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbRole generated by hbm2java
 */
@Entity
@Table(name = "TB_ROLE", schema = "dbo", catalog = "STAB_DEV")
public class TbRole implements java.io.Serializable {

	private long rleIdPk;
	private String rleName;
	private Set<TbUserRole> tbUserRoles = new HashSet<TbUserRole>(0);

	public TbRole() {
	}

	public TbRole(long rleIdPk) {
		this.rleIdPk = rleIdPk;
	}

	public TbRole(long rleIdPk, String rleName, Set<TbUserRole> tbUserRoles) {
		this.rleIdPk = rleIdPk;
		this.rleName = rleName;
		this.tbUserRoles = tbUserRoles;
	}

	@Id
	@Column(name = "RLE_ID_PK", unique = true, nullable = false)
	public long getRleIdPk() {
		return this.rleIdPk;
	}

	public void setRleIdPk(long rleIdPk) {
		this.rleIdPk = rleIdPk;
	}

	@Column(name = "RLE_NAME", length = 50)
	public String getRleName() {
		return this.rleName;
	}

	public void setRleName(String rleName) {
		this.rleName = rleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbRole")
	public Set<TbUserRole> getTbUserRoles() {
		return this.tbUserRoles;
	}

	public void setTbUserRoles(Set<TbUserRole> tbUserRoles) {
		this.tbUserRoles = tbUserRoles;
	}

}
