package com.sample.domain;
// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbTravelExpense generated by hbm2java
 */
@Entity
@Table(name = "TB_TRAVEL_EXPENSE", schema = "dbo", catalog = "STAB_DEV")
public class TbTravelExpense implements java.io.Serializable {

	private long expIdPk;
	private TbTravelPlan tbTravelPlan;
	private BigDecimal expNumLodging;
	private BigDecimal expNumTransportation;
	private BigDecimal expNumMeals;
	private BigDecimal expNumIncidentals;

	public TbTravelExpense() {
	}

	public TbTravelExpense(long expIdPk) {
		this.expIdPk = expIdPk;
	}

	public TbTravelExpense(long expIdPk, TbTravelPlan tbTravelPlan,
			BigDecimal expNumLodging, BigDecimal expNumTransportation,
			BigDecimal expNumMeals, BigDecimal expNumIncidentals) {
		this.expIdPk = expIdPk;
		this.tbTravelPlan = tbTravelPlan;
		this.expNumLodging = expNumLodging;
		this.expNumTransportation = expNumTransportation;
		this.expNumMeals = expNumMeals;
		this.expNumIncidentals = expNumIncidentals;
	}

	@Id
	@Column(name = "EXP_ID_PK", unique = true, nullable = false)
	public long getExpIdPk() {
		return this.expIdPk;
	}

	public void setExpIdPk(long expIdPk) {
		this.expIdPk = expIdPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXP_TRP_ID_FK")
	public TbTravelPlan getTbTravelPlan() {
		return this.tbTravelPlan;
	}

	public void setTbTravelPlan(TbTravelPlan tbTravelPlan) {
		this.tbTravelPlan = tbTravelPlan;
	}

	@Column(name = "EXP_NUM_LODGING", scale = 4)
	public BigDecimal getExpNumLodging() {
		return this.expNumLodging;
	}

	public void setExpNumLodging(BigDecimal expNumLodging) {
		this.expNumLodging = expNumLodging;
	}

	@Column(name = "EXP_NUM_TRANSPORTATION", scale = 4)
	public BigDecimal getExpNumTransportation() {
		return this.expNumTransportation;
	}

	public void setExpNumTransportation(BigDecimal expNumTransportation) {
		this.expNumTransportation = expNumTransportation;
	}

	@Column(name = "EXP_NUM_MEALS", scale = 4)
	public BigDecimal getExpNumMeals() {
		return this.expNumMeals;
	}

	public void setExpNumMeals(BigDecimal expNumMeals) {
		this.expNumMeals = expNumMeals;
	}

	@Column(name = "EXP_NUM_INCIDENTALS", scale = 4)
	public BigDecimal getExpNumIncidentals() {
		return this.expNumIncidentals;
	}

	public void setExpNumIncidentals(BigDecimal expNumIncidentals) {
		this.expNumIncidentals = expNumIncidentals;
	}

}
