package com.sample.domain;
// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbUniversity generated by hbm2java
 */
@Entity
@Table(name = "TB_UNIVERSITY", schema = "dbo", catalog = "STAB_DEV")
public class TbUniversity implements java.io.Serializable {

	private long uniIdPk;
	private String unistrName;
	private Set<TbProgram> tbPrograms = new HashSet<TbProgram>(0);

	public TbUniversity() {
	}

	public TbUniversity(long uniIdPk) {
		this.uniIdPk = uniIdPk;
	}

	public TbUniversity(long uniIdPk, String unistrName,
			Set<TbProgram> tbPrograms) {
		this.uniIdPk = uniIdPk;
		this.unistrName = unistrName;
		this.tbPrograms = tbPrograms;
	}

	@Id
	@Column(name = "UNI_ID_PK", unique = true, nullable = false)
	public long getUniIdPk() {
		return this.uniIdPk;
	}

	public void setUniIdPk(long uniIdPk) {
		this.uniIdPk = uniIdPk;
	}

	@Column(name = "UNISTR_NAME", length = 300)
	public String getUnistrName() {
		return this.unistrName;
	}

	public void setUnistrName(String unistrName) {
		this.unistrName = unistrName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUniversity")
	public Set<TbProgram> getTbPrograms() {
		return this.tbPrograms;
	}

	public void setTbPrograms(Set<TbProgram> tbPrograms) {
		this.tbPrograms = tbPrograms;
	}

}
