package com.sample.domain;
// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbUserProgram generated by hbm2java
 */
@Entity
@Table(name = "TB_USER_PROGRAM", schema = "dbo", catalog = "STAB_DEV")
public class TbUserProgram implements java.io.Serializable {

	private long usrPgmIdPk;
	private TbProgram tbProgram;
	private TbUser tbUser;
	private Integer usrPgmIntYear;
	private String usrPgmStrSemester;

	public TbUserProgram() {
	}

	public TbUserProgram(long usrPgmIdPk) {
		this.usrPgmIdPk = usrPgmIdPk;
	}

	public TbUserProgram(long usrPgmIdPk, TbProgram tbProgram, TbUser tbUser,
			Integer usrPgmIntYear, String usrPgmStrSemester) {
		this.usrPgmIdPk = usrPgmIdPk;
		this.tbProgram = tbProgram;
		this.tbUser = tbUser;
		this.usrPgmIntYear = usrPgmIntYear;
		this.usrPgmStrSemester = usrPgmStrSemester;
	}

	@Id
	@Column(name = "USR_PGM_ID_PK", unique = true, nullable = false)
	public long getUsrPgmIdPk() {
		return this.usrPgmIdPk;
	}

	public void setUsrPgmIdPk(long usrPgmIdPk) {
		this.usrPgmIdPk = usrPgmIdPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_PGM_PGMID_FK")
	public TbProgram getTbProgram() {
		return this.tbProgram;
	}

	public void setTbProgram(TbProgram tbProgram) {
		this.tbProgram = tbProgram;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_PGM_USRID_FK")
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Column(name = "USR_PGM_INT_YEAR")
	public Integer getUsrPgmIntYear() {
		return this.usrPgmIntYear;
	}

	public void setUsrPgmIntYear(Integer usrPgmIntYear) {
		this.usrPgmIntYear = usrPgmIntYear;
	}

	@Column(name = "USR_PGM_STR_SEMESTER", length = 10)
	public String getUsrPgmStrSemester() {
		return this.usrPgmStrSemester;
	}

	public void setUsrPgmStrSemester(String usrPgmStrSemester) {
		this.usrPgmStrSemester = usrPgmStrSemester;
	}

}
