package com.sample.domain;
// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbUserRole generated by hbm2java
 */
@Entity
@Table(name = "TB_USER_ROLE", schema = "dbo", catalog = "STAB_DEV")
public class TbUserRole implements java.io.Serializable {

	private long usrRleIdPk;
	private TbRole tbRole;
	private TbUser tbUser;

	public TbUserRole() {
	}

	public TbUserRole(long usrRleIdPk) {
		this.usrRleIdPk = usrRleIdPk;
	}

	public TbUserRole(long usrRleIdPk, TbRole tbRole, TbUser tbUser) {
		this.usrRleIdPk = usrRleIdPk;
		this.tbRole = tbRole;
		this.tbUser = tbUser;
	}

	@Id
	@Column(name = "USR_RLE_ID_PK", unique = true, nullable = false)
	public long getUsrRleIdPk() {
		return this.usrRleIdPk;
	}

	public void setUsrRleIdPk(long usrRleIdPk) {
		this.usrRleIdPk = usrRleIdPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RLE_ID_FK")
	public TbRole getTbRole() {
		return this.tbRole;
	}

	public void setTbRole(TbRole tbRole) {
		this.tbRole = tbRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_FK")
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

}
