package com.sample.domain;
// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbUser generated by hbm2java
 */
@Entity
@Table(name = "TB_USER", schema = "dbo", catalog = "STAB_DEV")
public class TbUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long usrUserIdPk;
	private String usrStrUserName;
	private String usrStrPassword;
	private String usrStrFirstName;
	private String usrStrMiddleName;
	private String usrStrLastName;
	private Date usrDtPwdExpiration;
	private Date usrDtRegistrationDate;
	private byte[] usrBoolStatus;
	private String usrStrMajor;
	private String usrStrMajor2;
	private String usrGender;
	private String usrDtExpectedGraduation;
	private String usrStrBlog;
	private Set<TbUsrProfileImages> tbUsrProfileImageses = new HashSet<TbUsrProfileImages>(
			0);
	private Set<TbTravelPlan> tbTravelPlans = new HashSet<TbTravelPlan>(0);
	private Set<TbUserRole> tbUserRoles = new HashSet<TbUserRole>(0);
	private Set<TbUserProgram> tbUserPrograms = new HashSet<TbUserProgram>(0);
	
	private byte[] imgUserImage;

	public TbUser() {
	}

	public TbUser(long usrUserIdPk) {
		this.usrUserIdPk = usrUserIdPk;
	}

	public TbUser(long usrUserIdPk, String usrStrUserName,
			String usrStrPassword, String usrStrFirstName,
			String usrStrMiddleName, String usrStrLastName,
			Date usrDtPwdExpiration, Date usrDtRegistrationDate,
			byte[] usrBoolStatus, String usrStrMajor, String usrStrMajor2,
			String usrGender, String usrDtExpectedGraduation,
			String usrStrBlog, Set<TbUsrProfileImages> tbUsrProfileImageses,
			Set<TbTravelPlan> tbTravelPlans, Set<TbUserRole> tbUserRoles,
			Set<TbUserProgram> tbUserPrograms) {
		this.usrUserIdPk = usrUserIdPk;
		this.usrStrUserName = usrStrUserName;
		this.usrStrPassword = usrStrPassword;
		this.usrStrFirstName = usrStrFirstName;
		this.usrStrMiddleName = usrStrMiddleName;
		this.usrStrLastName = usrStrLastName;
		this.usrDtPwdExpiration = usrDtPwdExpiration;
		this.usrDtRegistrationDate = usrDtRegistrationDate;
		this.usrBoolStatus = usrBoolStatus;
		this.usrStrMajor = usrStrMajor;
		this.usrStrMajor2 = usrStrMajor2;
		this.usrGender = usrGender;
		this.usrDtExpectedGraduation = usrDtExpectedGraduation;
		this.usrStrBlog = usrStrBlog;
		this.tbUsrProfileImageses = tbUsrProfileImageses;
		this.tbTravelPlans = tbTravelPlans;
		this.tbUserRoles = tbUserRoles;
		this.tbUserPrograms = tbUserPrograms;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "USR_USER_ID_PK", unique = true, nullable = false)
	public long getUsrUserIdPk() {
		return this.usrUserIdPk;
	}

	public void setUsrUserIdPk(long usrUserIdPk) {
		this.usrUserIdPk = usrUserIdPk;
	}

	@Column(name = "USR_STR_USER_NAME", length = 200)
	public String getUsrStrUserName() {
		return this.usrStrUserName;
	}

	public void setUsrStrUserName(String usrStrUserName) {
		this.usrStrUserName = usrStrUserName;
	}

	@Column(name = "USR_STR_PASSWORD", length = 200)
	public String getUsrStrPassword() {
		return this.usrStrPassword;
	}

	public void setUsrStrPassword(String usrStrPassword) {
		this.usrStrPassword = usrStrPassword;
	}

	@Column(name = "USR_STR_FIRST_NAME", length = 200)
	public String getUsrStrFirstName() {
		return this.usrStrFirstName;
	}

	public void setUsrStrFirstName(String usrStrFirstName) {
		this.usrStrFirstName = usrStrFirstName;
	}

	@Column(name = "USR_STR_MIDDLE_NAME", length = 200)
	public String getUsrStrMiddleName() {
		return this.usrStrMiddleName;
	}

	public void setUsrStrMiddleName(String usrStrMiddleName) {
		this.usrStrMiddleName = usrStrMiddleName;
	}

	@Column(name = "USR_STR_LAST_NAME", length = 200)
	public String getUsrStrLastName() {
		return this.usrStrLastName;
	}

	public void setUsrStrLastName(String usrStrLastName) {
		this.usrStrLastName = usrStrLastName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USR_DT_PWD_EXPIRATION", length = 23)
	public Date getUsrDtPwdExpiration() {
		return this.usrDtPwdExpiration;
	}

	public void setUsrDtPwdExpiration(Date usrDtPwdExpiration) {
		this.usrDtPwdExpiration = usrDtPwdExpiration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "USR_DT_REGISTRATION_DATE", length = 23)
	public Date getUsrDtRegistrationDate() {
		return this.usrDtRegistrationDate;
	}

	public void setUsrDtRegistrationDate(Date usrDtRegistrationDate) {
		this.usrDtRegistrationDate = usrDtRegistrationDate;
	}

	@Column(name = "USR_BOOL_STATUS")
	public byte[] getUsrBoolStatus() {
		return this.usrBoolStatus;
	}

	public void setUsrBoolStatus(byte[] usrBoolStatus) {
		this.usrBoolStatus = usrBoolStatus;
	}

	@Column(name = "USR_STR_MAJOR", length = 200)
	public String getUsrStrMajor() {
		return this.usrStrMajor;
	}

	public void setUsrStrMajor(String usrStrMajor) {
		this.usrStrMajor = usrStrMajor;
	}

	@Column(name = "USR_STR_MAJOR2", length = 200)
	public String getUsrStrMajor2() {
		return this.usrStrMajor2;
	}

	public void setUsrStrMajor2(String usrStrMajor2) {
		this.usrStrMajor2 = usrStrMajor2;
	}

	@Column(name = "USR_GENDER", length = 1)
	public String getUsrGender() {
		return this.usrGender;
	}

	public void setUsrGender(String usrGender) {
		this.usrGender = usrGender;
	}

	@Column(name = "USR_DT_EXPECTED_GRADUATION", length = 10)
	public String getUsrDtExpectedGraduation() {
		return this.usrDtExpectedGraduation;
	}

	public void setUsrDtExpectedGraduation(String usrDtExpectedGraduation) {
		this.usrDtExpectedGraduation = usrDtExpectedGraduation;
	}

	@Column(name = "USR_STR_BLOG", length = 200)
	public String getUsrStrBlog() {
		return this.usrStrBlog;
	}

	public void setUsrStrBlog(String usrStrBlog) {
		this.usrStrBlog = usrStrBlog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbUsrProfileImages> getTbUsrProfileImageses() {
		return this.tbUsrProfileImageses;
	}

	public void setTbUsrProfileImageses(
			Set<TbUsrProfileImages> tbUsrProfileImageses) {
		this.tbUsrProfileImageses = tbUsrProfileImageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbTravelPlan> getTbTravelPlans() {
		return this.tbTravelPlans;
	}

	public void setTbTravelPlans(Set<TbTravelPlan> tbTravelPlans) {
		this.tbTravelPlans = tbTravelPlans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbUserRole> getTbUserRoles() {
		return this.tbUserRoles;
	}

	public void setTbUserRoles(Set<TbUserRole> tbUserRoles) {
		this.tbUserRoles = tbUserRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbUser")
	public Set<TbUserProgram> getTbUserPrograms() {
		return this.tbUserPrograms;
	}

	public void setTbUserPrograms(Set<TbUserProgram> tbUserPrograms) {
		this.tbUserPrograms = tbUserPrograms;
	}
	
	@Column(name = "IMG_USER_IMAGE")
	public byte[] getImgUserImage() {
		return this.imgUserImage;
	}

	public void setImgUserImage(byte[] imgUserImage) {
		this.imgUserImage = imgUserImage;
	}

}
