package com.sample.domain;
// default package
// Generated Feb 9, 2014 3:05:22 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbUsrProfileImages generated by hbm2java
 */
@Entity
@Table(name = "TB_USR_PROFILE_IMAGES", schema = "dbo", catalog = "STAB_DEV")
public class TbUsrProfileImages implements java.io.Serializable {

	private long imgIdPk;
	private TbUser tbUser;
	private byte[] imgUserImage;

	public TbUsrProfileImages() {
	}

	public TbUsrProfileImages(long imgIdPk) {
		this.imgIdPk = imgIdPk;
	}

	public TbUsrProfileImages(long imgIdPk, TbUser tbUser, byte[] imgUserImage) {
		this.imgIdPk = imgIdPk;
		this.tbUser = tbUser;
		this.imgUserImage = imgUserImage;
	}

	@Id
	@Column(name = "IMG_ID_PK", unique = true, nullable = false)
	public long getImgIdPk() {
		return this.imgIdPk;
	}

	public void setImgIdPk(long imgIdPk) {
		this.imgIdPk = imgIdPk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IMG_USR_ID_FK")
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Column(name = "IMG_USER_IMAGE")
	public byte[] getImgUserImage() {
		return this.imgUserImage;
	}

	public void setImgUserImage(byte[] imgUserImage) {
		this.imgUserImage = imgUserImage;
	}

}
